apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: argocd
  source:
    repoURL: https://github.com/vermyterr/k8s.git
    path: argocd-install/argo-cd
    targetRevision: main
    helm:
      version: v3
      valueFiles:
      - values.yaml
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  syncPolicy:
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argo-cd
spec:
  project: argo-cd
  source:
    repoURL: https://github.com/vermyterr/k8s.git
    path: argocd-apps
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appprojects
  namespace: argo-cd
spec:
  project: argo-cd
  source:
    repoURL: https://github.com/vermyterr/k8s.git
    path: argocd-appprojects
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
