apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/vermyterr/k8s.git
  name: argocd-github
  type: git